str = "I eat {0} apples".format(3)
print(str)
str = "{0:<10}".format("hi")
print(str)
str = "{0:>10}".format("hi")
print(str)
str = "{0:^10}".format("hi")
print(str)
str = "{0:=>10}".format("hi")
print(str)
str = "{0:=>10}".format("hi~~~")
print(str)
str = "{0:=>10}".format("hi~ there")
print(str)
str = "{0:=>10}".format("hi~ there!")
print(str)
